version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    ports:
      - "5432:5432"
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
